import type { NextPage } from "next";
import Head from "next/head";
import styles from "./Contato.module.scss";
import Header from "../components/Header/Header";

const Contato: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/avegra" rel="stylesheet" />
      </Head>

      <Header/>
      <main className={styles.main}>
        <div className={styles.content}>
          <span>Contato</span>
        </div>
        <footer className={styles.footer}>
          Isabela Alves, 2022 - Todos os direitos reservados ©
        </footer>
      </main>
    </>
  );
};

export default Contato;
